FROM registry.access.redhat.com/rhel7:latest
MAINTAINER Rolando Carrasco <rcarrasco@spsolutions.com.mx>

ENV JAVA_VERSION=${JAVA_VERSION:-1.8.0} \
    JAVA_TYPE=${JAVA_TYPE:-oracle}

ENV JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-${JAVA_TYPE}
